# Copyright (c) 2026 K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

defmodule Serials.VSekaiFabric do
  use RFD.Register

  register "VSekaiFabric" do
    layer arc: "1.3.6.1.4.1.66606.1.2",
          site: 2,
          site_name: "v-sekai-fabric",
          category: 1,
          category_name: "documents",
          pen: "1.3.6.1.4.1.66606",
          rule: "rfd/2000-conventions/index.md",
          note:
            {:reactivated,
             "Reactivated 2026-08-31 when site 1 was frozen. The site was decommissioned on 2026-08-29 and moved into request-for-discussion, which is where its register now lives; the 2026-08-29 sentence promising no new allocations was retracted in pen-66606.usda sitesDecommissioned. From 2026-08-31 forward this is the workspace source of new RFD serials -- new RFDs get 2NNN numbers here."}

    thesis "Every serial this site has allocated. A serial is appended once. It is never removed and never reused, because it is the last arc of an OID and an arc names one document for as long as it exists. A slug follows its directory, because a retitle renames a document and does not renumber it."

    allocated do
      serial 2001, "zonefabric-roadmap-vs-mas-bandwidth-fps"
      serial 2002, "taskweft-value-narrowing-primitives-and-refs"
      serial 2004, "castspell-libgodot-sandbox-runtime-scope"
      serial 2005, "gltf-interactivity-value-type-taxonomy-correction"
      serial 2006, "cockroachdb-with-mtls-role-separation"
      serial 2008, "webtransport-over-quic-for-game-traffic"
      serial 2009, "ghcr-package-ownership-same-repo"
      serial 2010, "maglev-cycle-1-gateway-handshake"
      serial 2012, "amend-pr-before-it-enters-the-queue"
      serial 2013, "archival-file-naming-convention"
      serial 2014, "art-game-loop-steel-thread"
      serial 2015, "bounded-llm-steering-queue"
      serial 2016, "checking-sccache"
      serial 2017, "compiling-godot-engine"
      serial 2018, "feature-classification-poc-baseline-stretch"
      serial 2019, "gitassembly-tag-release"
      serial 2020, "pin-engine-to-frozen-godot-4-7"
      serial 2021, "require-pr-and-merge-queue-on-main"
      serial 2023, "webtransport-http3-transport"
      serial 2024, "windows-background-services-nssm"
      serial 2025, "tenseless-continuous-present-voice"
      serial 2026, "commit-messages-sentence-case"
      serial 2027, "umbrella-package-installs-all-components"
      serial 2028, "hexagonal-core-ports-adapters"
      serial 2030, "cicd-runners-as-queueing-system"
      serial 2032, "core-codegen-lean-slang"
      serial 2033, "core-contract-pure-reducer-byte-state"
      serial 2036, "forward-renderer-baked-light"
      serial 2040, "hexagon-combat-core"
      serial 2044, "lean4-kernel-cores-flat-c-host-adapters"
      serial 2045, "loot-action-core-loop-mvp-vertical-slice"
      serial 2051, "headless-openxr-testing-with-monado"
      serial 2052, "http3-listener-session-findings"
      serial 2053, "integral-entity-transform-wire"
      serial 2057, "vertical-slice-repository-map"
      serial 2058, "webtransport-persistent-framed-stream"
      serial 2059, "bad-news-reports-lead-with-the-bottom-line"
      serial 2060, "org-scoped-github-app-token-for-gh-access"
      serial 2062, "repository-and-capability-inventory"
      serial 2064, "kebab-case-repos-snake-case-local-checkouts"
      serial 2065, "fabric-platform-central-elixir-burrito-casync"
      serial 2066, "game-loop-cluster-sequence"
      serial 2067, "release-tag-progression-dev-beta-rc"
      serial 2068, "sccache-github-actions-cache-for-godot-builds"
      serial 2069, "defer-loot-slice-hardening-until-needed"
      serial 2070, "loop-slice-telemetry-to-the-observability-collector"
      serial 2072, "actor-lite-worker-pool"
      serial 2073, "async-fdb-callback-chain"
      serial 2074, "binary-value-encoding-for-fdb"
      serial 2075, "fdb-over-cockroachdb-for-zone-state"
      serial 2076, "macaroon-xdp-security"
      serial 2077, "pert-critical-path-zonefabric"
      serial 2078, "plausible-witness-dag-feature-ablation"
      serial 2079, "sandboxed-godot-in-zone-server-h2o-via-raw-libriscv"
      serial 2080, "slotmap-entity-storage"
      serial 2081, "three-layer-verification-strategy"
      serial 2082, "zonefabric-scaling"
      serial 2083, "zone-server-h2o-replaces-godot-fabriczone"
      serial 2084, "zstd-compression-for-zone-state"
      serial 2085, "the-gyre-mud-setting-on-the-loot-action-shell"
      serial 2086, "defer-nogod-gossip-zone-authority"
      serial 2087, "avatar-ik-sinew-mocap-align-over-mink"
      serial 2089, "flyio-over-podman-quadlets"
      serial 2090, "uro-burrito-release"
      serial 2091, "the-gyre-mud-domain-and-mode-selector"
      serial 2092, "rebac-gates-libriscv-guest-access"
      serial 2093, "compile-taskweft-to-linear-automata"
      serial 2096, "guest-transport-measured-on-fly"
      serial 2097, "pubsub-belongs-in-userspace"
      serial 2098, "rollback-snapshot-budget"
      serial 2101, "zstd-delta-on-the-wire"
      serial 2103, "uro-on-ecto-foundationdb"
      serial 2105, "archive-self-host-era-support-repos"
      serial 2106, "split-the-archive-into-its-own-repo"
      serial 2108, "local-cabi-guests-and-in-tick-fanout"
      serial 2109, "two-tiers-with-foundationdb-as-the-store"
      serial 2110, "h2o-libriscv-as-a-rivet-actor"
      serial 2111, "convert-the-deployment-words"
      serial 2112, "lexical-for-the-slash-command-interface"
      serial 2113, "foundationdb-on-windows-built-from-source"
      serial 2114, "prove-the-store-by-breaking-it"
      serial 2115, "a-planner-domain-document-is-a-cheap-layer-surface"
      serial 2116, "elixir-epoll-zone-server-in-the-h2o-style"
      serial 2117, "retire-the-h2o-tier-record-set"
      serial 2118, "a-baker-replaces-the-godot-editor"
      serial 2119, "salvage-you-can-hold"
      serial 2120, "the-gyre-became-a-settlement-game"
      serial 2121, "amend-rfd-2111-against-the-tree"
      serial 2123, "a-second-webtransport-implementation"
      serial 2124, "elixir-error-tuples-in-every-reply"
      serial 2134, "cluster-tls-is-decided-before-data"
      serial 2135, "checks-run-where-the-credentials-already-are"
      serial 2136, "the-gacha-critical-path"
      serial 2137, "rfd-reports-share-one-sheet"
      serial 2140, "openbao-on-foundationdb"
      serial 2141, "fdb-tls-rotation-without-data-loss"
      serial 2142, "bao-pki-zerotrust-service-tls"
      serial 2143, "fdb-backup-fans-out-to-r2"
      serial 2144, "fdb-dr-runbook-first-run"
      serial 2145, "certificate-lifetimes"
      serial 2146, "bao-is-the-secret-store"
      serial 2147, "bao-is-critical-infrastructure"
      serial 2148, "grafcet-as-taskwefts-authoring-surface"
      serial 2149, "grafcet-static-analysis-in-lean4"
      serial 2150, "rectgtn-on-openplc4-over-coap-oscore"
      serial 2152, "or-divergence-plcopen-emit"
      serial 2153, "fbd-to-nodegraph-converters"
      serial 2154, "openplc4-to-godot-sandbox"
      serial 2155, "gdscript-fbd-transpiler"
      serial 2156, "safegdscript-compile-step"
      serial 2157, "fbd-to-elf-compiler-in-lean4"
      serial 2159, "fbd-compiler-two-implementations"
      serial 2160, "openusd-as-taskweft-intermediate"
      serial 2161, "vn-avatar-cleanroom-on-maskscore"
      serial 2162, "maskscore-usdz-skinning-and-15-edit-emit", flight_level: :l1
      serial 2163, "maskscore-text-stub-gemma-vlm", flight_level: :l1
      serial 2164, "maskscore-speech-stub-panel-and-cloning", flight_level: :l1
      serial 2165, "maskscore-unified-8-stub-emit", flight_level: :l1
      serial 2166, "maskscore-cineform-mkv-bundle", flight_level: :l1
      serial 2167, "maskscore-voice-reward-distillation", flight_level: :l1
      serial 2168, "retract-wholebody-detector-keep-renderer", flight_level: :l1
      serial 2169, "abandon-strangler-fig-studio-core"
      serial 2170, "allosaurus-squad-localization-langs", flight_level: :l2
      serial 2171, "atelier-workshop-shuttle-vocabulary", flight_level: :l2
      serial 2172, "tenseless-continuous-present-voice", flight_level: :l2
      serial 2173, "qwen3-vl-to-gemma-migration-index"
      serial 2174, "abandoned-citation-index"
      serial 2175, "abandon-rented-compute-rfds"
      serial 2176, "committed-cites-terminal-index"
      serial 2177, "flight-levels-taxonomy"
      serial 2178, "qaft-4bit-across-the-stack"
      serial 2179, "drop-whisper-models"
      serial 2180, "drop-gemma-auto"
      serial 2181, "drop-allosaurus-rus"
      serial 2182, "identity-triangle-operator-market-customer", flight_level: :l2
      serial 2183, "retrain-omnigen-for-layer-decomposition"
      serial 2184, "omnigen2-sdcpp-port-lean4-verified"
      serial 2185, "hierarchical-oid-part-registry"
      serial 2186, "omnigen2-to-lumina2-lora-transfer-qaft"
      serial 2187, "identity-anny-via-omnigen2"
      serial 2188, "one-ggml-across-workspace"
      serial 2189, "stick-figure-sanity-check-for-pose-corpus"
      serial 2190, "multi-camera-rig-extrinsics-calibration"
      serial 2191, "unrolled-solver-residual-measurement"
      serial 2192, "rfdetr-keypoint-weights-licence-verification"
      serial 2193, "editscore-as-constructed-synthetic-reproducibility-bar"
      serial 2195, "weftspun-bao-tailscale-sidecar"
      serial 2196, "huggingface-dataset-viewer-rules"
      serial 2197, "maskscore-rung-1-bootstrap-hf-restructure"
      serial 2200, "rebac-agent-roles"
      serial 2201, "coordinate-agents-ceremony"
      serial 2202, "rebac-bao-enforcement"
      serial 2203, "anny-soma-first-subset-corpus-shape"
      serial 2198, "lladao-speed-work-for-dressing-overlay"
      serial 2199, "hailo-real-4bit-qat"
      serial 2204, "rectgtn-fleet-coordination"
      serial 2205, "taskweft-in-bao"
      serial 2206, "video-call-vrm-portrait"
      serial 2207, "nord-palette-for-demos"
      serial 2209, "cc-by-nc-blocklist-entry"
      serial 2210, "atelier-godot-web-shipping-surface", flight_level: :l2
      serial 2211, "base-tree-entities-godot-sandbox"
      serial 2213, "vrm-via-godot-sandbox-elf"
      serial 2214, "model-bundle-sqlite-range-fetch-zstd"
      serial 2215, "one-binary-two-heads"
      serial 2216, "threejs-blocklist"
      serial 2229, "interchangeable-parts-consolidation", flight_level: :l3
      serial 2230, "ggml-adapters-in-godot-sandbox"
      serial 2232, "rfd-dsl-in-elixir", flight_level: :l2
      serial 2233, "close-out-gates-red-green-scout"
      serial 2234, "dress-on-pipeline"
      serial 2235, "taskweft-acp-agent"
      serial 2236, "fbd-teacher-in-three-steps"
      serial 2237, "body-scan-controller"
      serial 2238, "g1-sim-to-real-environment"
      serial 2239, "traits-and-one-binary"
      serial 2240, "citation-metadata-and-review-interchange"
      serial 2241, "audio-pose-from-speaking-faces", flight_level: :l2
      serial 2242, "ggml-consumers-as-native-godot-modules", flight_level: :l2
      serial 2243, "assembly-one-cycle-blockers", flight_level: :l2
      serial 2244, "one-deformation-operator"
      serial 2245, "webgpu-allowed-inside-godot-engine"
      serial 2246, "editscore-omnigen-bootstrap-for-unmapped-parts"
    end

    deleted do
      serial 2000, "conventions"
      serial 2003, "castspell-sandbox-package-and-manifest-encoding"
      serial 2007, "godot-double-precision-template-release-for-zone"
      serial 2022, "spatial-audio-patched-resonance-audio"
      serial 2029, "cassie-desktop-curvenet-authoring"
      serial 2031, "content-build-merged-double-precision-mcp"
      serial 2034, "deterministic-cores-integer-seeded-rng"
      serial 2035, "first-party-curated-content-zone-baker-budgets"
      serial 2037, "generated-behavior-sandboxed-riscv"
      serial 2038, "genre-generic-naming-no-trademarks"
      serial 2039, "hexagon-budgeter-core"
      serial 2041, "hexagon-loot-core"
      serial 2042, "hexagon-presence-core"
      serial 2043, "hexagon-progression-core"
      serial 2046, "server-authoritative-simulation-deferred-rollback"
      serial 2047, "webtransportd-core-transport-adapter"
      serial 2048, "android-template-temurin-jdk21"
      serial 2049, "fabric-channels-as-reliability-classes"
      serial 2050, "five-second-transaction-limit"
      serial 2054, "mcp-runtime-bridge-deployed-builds"
      serial 2055, "r128-fixed-point-as-lean-library"
      serial 2056, "systemd-quadlet-verification-queue"
      serial 2063, "repo-markdown-single-source-of-truth-for-project-state"
      serial 2071, "yagni-times-structure-to-need"
      serial 2088, "picoquic-picotls-transport-for-zone-server-h2o"
      serial 2094, "minimum-ugc-game-loop-guest-composition"
      serial 2095, "two-guest-classes-domain-abi-and-bubblewrap"
      serial 2099, "server-authority-on-fly"
      serial 2100, "tick-rate-send-rate-and-the-bone-budget"
      serial 2102, "the-whole-deployment-on-15-usd"
      serial 2107, "janet-scripting-over-a-c-taskweft-core"
      serial 2122, "the-client-is-native"
      serial 2125, "an-interactor-in-another-process"
      serial 2126, "two-see-through-interactors"
      serial 2127, "a-service-is-not-a-side"
      serial 2128, "the-release-ladder-is-not-automated"
      serial 2129, "cost-and-latency-are-two-budgets"
      serial 2130, "state-what-a-repository-is-made-of"
      serial 2132, "a-permission-cannot-be-granted-sideways"
      serial 2133, "the-pool-rents-from-the-spot-book"
      serial 2138, "interactor-shuttle-merges-spot-broker-and-uro"
      serial 2139, "maskscore-qaft-budget"
      serial 2151, "coap-oscore-nif-for-taskweft"
      serial 2158, "lean4-fbd-compiler-self-hosted-on-riscv"
      serial 2194, "atelier-shuttle-portfolio-widget"
      serial 2208, "decision-point-control-surface"
      serial 2212, "motion-bricks-as-native-godot-module"
      serial 2217, "ggml-webgl2-backend-evaluation"
      serial 2218, "ggml-webgpu-backend"
      serial 2227, "workspace-ggml-models-on-platform-web-webgpu"
      serial 2228, "webgpu-native-drop-platform-web", flight_level: :l2
      serial 2231, "drop-webgpu-use-vulkan", flight_level: :l2
    end
  end
end
